package org.ditw.learning.akkastr.affcountry

import org.json4s.DefaultFormats

object CountryData {

  object CountryEnum extends Enumeration {
    type CountryEnum = Value

    val AD,
    AE,
    AF,
    AG,
    AI,
    AL,
    AM,
    AO,
    AQ,
    AR,
    AS,
    AT,
    AU,
    AW,
    AX,
    AZ,
    BA,
    BB,
    BD,
    BE,
    BF,
    BG,
    BH,
    BI,
    BJ,
    BL,
    BM,
    BN,
    BO,
    BQ,
    BR,
    BS,
    BT,
    BV,
    BW,
    BY,
    BZ,
    CA,
    CC,
    CD,
    CF,
    CG,
    CH,
    CI,
    CK,
    CL,
    CM,
    CN,
    CO,
    CR,
    CU,
    CV,
    CW,
    CX,
    CY,
    CZ,
    DE,
    DJ,
    DK,
    DM,
    DO,
    DZ,
    EC,
    EE,
    EG,
    EH,
    ER,
    ES,
    ET,
    FI,
    FJ,
    FK,
    FM,
    FO,
    FR,
    GA,
    GB,
    GD,
    GE,
    GF,
    GG,
    GH,
    GI,
    GL,
    GM,
    GN,
    GP,
    GQ,
    GR,
    GS,
    GT,
    GU,
    GW,
    GY,
    HK,
    HM,
    HN,
    HR,
    HT,
    HU,
    ID,
    IE,
    IL,
    IM,
    IN,
    IO,
    IQ,
    IR,
    IS,
    IT,
    JE,
    JM,
    JO,
    JP,
    KE,
    KG,
    KH,
    KI,
    KM,
    KN,
    KP,
    KR,
    KW,
    KY,
    KZ,
    LA,
    LB,
    LC,
    LI,
    LK,
    LR,
    LS,
    LT,
    LU,
    LV,
    LY,
    MA,
    MC,
    MD,
    ME,
    MF,
    MG,
    MH,
    MK,
    ML,
    MM,
    MN,
    MO,
    MP,
    MQ,
    MR,
    MS,
    MT,
    MU,
    MV,
    MW,
    MX,
    MY,
    MZ,
    NA,
    NC,
    NE,
    NF,
    NG,
    NI,
    NL,
    NO,
    NP,
    NR,
    NU,
    NZ,
    OM,
    PA,
    PE,
    PF,
    PG,
    PH,
    PK,
    PL,
    PM,
    PN,
    PR,
    PS,
    PT,
    PW,
    PY,
    QA,
    RE,
    RO,
    RS,
    RU,
    RW,
    SA,
    SB,
    SC,
    SD,
    SE,
    SG,
    SH,
    SI,
    SJ,
    SK,
    SL,
    SM,
    SN,
    SO,
    SR,
    SS,
    ST,
    SV,
    SX,
    SY,
    SZ,
    TC,
    TD,
    TF,
    TG,
    TH,
    TJ,
    TK,
    TL,
    TM,
    TN,
    TO,
    TR,
    TT,
    TV,
    TW,
    TZ,
    UA,
    UG,
    UM,
    US,
    UY,
    UZ,
    VA,
    VC,
    VE,
    VG,
    VI,
    VN,
    VU,
    WF,
    WS,
    XK,
    YE,
    YT,
    ZA,
    ZM,
    ZW,

    TODO = Value
  }

  import CountryEnum._

  val jsons =
    """
      |[
      |  {"cc":"AF","name":"Afghanistan","synonyms":[]},
      |  {"cc":"AX","name":"Åland Islands","synonyms":[]},
      |  {"cc":"AL","name":"Albania","synonyms":[]},
      |  {"cc":"DZ","name":"Algeria","synonyms":[ "Algérie" ]},
      |  {"cc":"AS","name":"American Samoa","synonyms":[]},
      |  {"cc":"AD","name":"Andorra","synonyms":[]},
      |  {"cc":"AO","name":"Angola","synonyms":[]},
      |  {"cc":"AI","name":"Anguilla","synonyms":[]},
      |  {"cc":"AQ","name":"Antarctica","synonyms":[]},
      |  {"cc":"AG","name":"Antigua and Barbuda","synonyms":[]},
      |  {"cc":"AR","name":"Argentina","synonyms":[]},
      |  {"cc":"AM","name":"Armenia","synonyms":[]},
      |  {"cc":"AW","name":"Aruba","synonyms":[]},
      |  {"cc":"AU","name":"Australia","synonyms":[]},
      |  {"cc":"AT","name":"Austria","synonyms":[ "Osterreich" ]},
      |  {"cc":"AZ","name":"Azerbaijan","synonyms":[]},
      |  {"cc":"BS","name":"Bahamas","synonyms":[ "The Bahamas" ]},
      |  {"cc":"BH","name":"Bahrain","synonyms":[ "Kingdom of Bahrain" ]},
      |  {"cc":"BD","name":"Bangladesh","synonyms":[]},
      |  {"cc":"BB","name":"Barbados","synonyms":[]},
      |  {"cc":"BY","name":"Belarus","synonyms":[]},
      |  {"cc":"BE","name":"Belgium","synonyms":[ "Belgique" ]},
      |  {"cc":"BZ","name":"Belize","synonyms":[]},
      |  {"cc":"BJ","name":"Benin","synonyms":[]},
      |  {"cc":"BM","name":"Bermuda","synonyms":[]},
      |  {"cc":"BT","name":"Bhutan","synonyms":[]},
      |  {"cc":"BO","name":"Bolivia","synonyms":[]},
      |  {"cc":"BQ","name":"Bonaire","synonyms":[]},
      |  {"cc":"BA","name":"Bosnia and Herzegovina","synonyms":[]},
      |  {"cc":"BW","name":"Botswana","synonyms":[]},
      |  {"cc":"BV","name":"Bouvet Island","synonyms":[]},
      |  {"cc":"BR","name":"Brazil","synonyms":[]},
      |  {"cc":"IO","name":"British Indian Ocean Territory","synonyms":[]},
      |  {"cc":"BN","name":"Brunei Darussalam","synonyms":[ "Brunei" ]},
      |  {"cc":"BG","name":"Bulgaria","synonyms":[]},
      |  {"cc":"BF","name":"Burkina Faso","synonyms":[]},
      |  {"cc":"BI","name":"Burundi","synonyms":[]},
      |  {"cc":"KH","name":"Cambodia","synonyms":[]},
      |  {"cc":"CM","name":"Cameroon","synonyms":[]},
      |  {"cc":"CA","name":"Canada","synonyms":[]},
      |  {"cc":"CV","name":"Cape Verde","synonyms":[]},
      |  {"cc":"KY","name":"Cayman Islands","synonyms":[]},
      |  {"cc":"CF","name":"Central African Republic","synonyms":[]},
      |  {"cc":"TD","name":"Chad","synonyms":[]},
      |  {"cc":"CL","name":"Chile","synonyms":[]},
      |  {"cc":"CN","name":"China","synonyms":[
      |    "The People's Republic of China",
      |    "People's Republic of China",
      |    "PRC",
      |    "P.R.C.",
      |    "PR China",
      |    "P R China"
      |  ]},
      |  {"cc":"CX","name":"Christmas Island","synonyms":[]},
      |  {"cc":"CC","name":"Cocos (Keeling) Islands","synonyms":[]},
      |  {"cc":"CO","name":"Colombia","synonyms":[]},
      |  {"cc":"KM","name":"Comoros","synonyms":[]},
      |  {"cc":"CD","name":"Congo","synonyms":[]},
      |  {"cc":"CK","name":"Cook Islands","synonyms":[]},
      |  {"cc":"CR","name":"Costa Rica","synonyms":[]},
      |  {"cc":"CI","name":"Côte d’Ivoire","synonyms":[]},
      |  {"cc":"HR","name":"Croatia","synonyms":[]},
      |  {"cc":"CU","name":"Cuba","synonyms":[]},
      |  {"cc":"CW","name":"Curaçao","synonyms":[]},
      |  {"cc":"CY","name":"Cyprus","synonyms":[]},
      |  {"cc":"CZ","name":"Czech Republic","synonyms":[]},
      |  {"cc":"DK","name":"Denmark","synonyms":[ "Dänemark" ]},
      |  {"cc":"DJ","name":"Djibouti","synonyms":[]},
      |  {"cc":"DM","name":"Dominica","synonyms":[]},
      |  {"cc":"DO","name":"Dominican Republic","synonyms":[]},
      |  {"cc":"EC","name":"Ecuador","synonyms":[]},
      |  {"cc":"EG","name":"Egypt","synonyms":[]},
      |  {"cc":"SV","name":"El Salvador","synonyms":[]},
      |  {"cc":"GQ","name":"Equatorial Guinea","synonyms":[]},
      |  {"cc":"ER","name":"Eritrea","synonyms":[]},
      |  {"cc":"EE","name":"Estonia","synonyms":[]},
      |  {"cc":"ET","name":"Ethiopia","synonyms":[]},
      |  {"cc":"FK","name":"Falkland Islands","synonyms":[]},
      |  {"cc":"FO","name":"Faroe Islands","synonyms":[]},
      |  {"cc":"FJ","name":"Fiji","synonyms":[]},
      |  {"cc":"FI","name":"Finland","synonyms":[]},
      |  {"cc":"FR","name":"France","synonyms":[ "Frankreich" ]},
      |  {"cc":"GF","name":"French Guiana","synonyms":[]},
      |  {"cc":"PF","name":"French Polynesia","synonyms":[]},
      |  {"cc":"TF","name":"French Southern Territories","synonyms":[]},
      |  {"cc":"GA","name":"Gabon","synonyms":[]},
      |  {"cc":"GM","name":"Gambia","synonyms":[]},
      |  {
      |    "cc":"DE","name":"Germany",
      |    "synonyms":[
      |      "West Germany", "Federal Republic of Germany", "W.-Germany", "Deutschland"
      |    ]
      |  },
      |  {"cc":"GH","name":"Ghana","synonyms":[]},
      |  {"cc":"GI","name":"Gibraltar","synonyms":[]},
      |  {"cc":"GR","name":"Greece","synonyms":[]},
      |  {"cc":"GL","name":"Greenland","synonyms":[]},
      |  {"cc":"GD","name":"Grenada","synonyms":[]},
      |  {"cc":"GP","name":"Guadeloupe","synonyms":[]},
      |  {"cc":"GU","name":"Guam","synonyms":[]},
      |  {"cc":"GT","name":"Guatemala","synonyms":[]},
      |  {"cc":"GG","name":"Guernsey","synonyms":[]},
      |  {"cc":"GN","name":"Guinea","synonyms":[]},
      |  {"cc":"GW","name":"Guinea-Bissau","synonyms":[]},
      |  {"cc":"GY","name":"Guyana","synonyms":[]},
      |  {"cc":"HT","name":"Haiti","synonyms":[]},
      |  {"cc":"HM","name":"Heard Island and Mcdonald Islands","synonyms":[]},
      |  {"cc":"VA","name":"Vatican City","synonyms":[]},
      |  {"cc":"HN","name":"Honduras","synonyms":[]},
      |  {"cc":"HK","name":"Hong Kong","synonyms":[]},
      |  {"cc":"HU","name":"Hungary","synonyms":[]},
      |  {"cc":"IS","name":"Iceland","synonyms":[]},
      |  {"cc":"IN","name":"India","synonyms":[]},
      |  {"cc":"ID","name":"Indonesia","synonyms":[]},
      |  {"cc":"IR","name":"Iran","synonyms":[]},
      |  {"cc":"IQ","name":"Iraq","synonyms":[]},
      |  {"cc":"IE","name":"Ireland","synonyms":[ "Republic of Ireland" ]},
      |  {"cc":"IM","name":"Isle of Man","synonyms":[]},
      |  {"cc":"IL","name":"Israel","synonyms":[]},
      |  {"cc":"IT","name":"Italy","synonyms":[ "Italia" ]},
      |  {"cc":"JM","name":"Jamaica","synonyms":[]},
      |  {"cc":"JP","name":"Japan","synonyms":[]},
      |  {"cc":"JO","name":"Jordan","synonyms":[]},
      |  {"cc":"KZ","name":"Kazakhstan","synonyms":[]},
      |  {"cc":"KE","name":"Kenya","synonyms":[]},
      |  {"cc":"KI","name":"Kiribati","synonyms":[]},
      |  {"cc":"KP","name":"North Korea","synonyms":[]},
      |  {"cc":"KR","name":"South Korea","synonyms":[ "Korea", "Republic of Korea" ]},
      |  {"cc":"KW","name":"Kuwait","synonyms":[]},
      |  {"cc":"KG","name":"Kyrgyzstan","synonyms":[]},
      |  {"cc":"LA","name":"Lao People's Democratic Republic","synonyms":[]},
      |  {"cc":"LV","name":"Latvia","synonyms":[]},
      |  {"cc":"LB","name":"Lebanon","synonyms":[]},
      |  {"cc":"LS","name":"Lesotho","synonyms":[]},
      |  {"cc":"LR","name":"Liberia","synonyms":[]},
      |  {"cc":"LY","name":"Libya","synonyms":[]},
      |  {"cc":"LI","name":"Liechtenstein","synonyms":[]},
      |  {"cc":"LT","name":"Lithuania","synonyms":[]},
      |  {"cc":"LU","name":"Luxembourg","synonyms":[]},
      |  {"cc":"MO","name":"Macao","synonyms":[]},
      |  {"cc":"MK","name":"Macedonia","synonyms":[]},
      |  {"cc":"MG","name":"Madagascar","synonyms":[]},
      |  {"cc":"MW","name":"Malawi","synonyms":[]},
      |  {"cc":"MY","name":"Malaysia","synonyms":[]},
      |  {"cc":"MV","name":"Maldives","synonyms":[]},
      |  {"cc":"ML","name":"Mali","synonyms":[]},
      |  {"cc":"MT","name":"Malta","synonyms":[]},
      |  {"cc":"MH","name":"Marshall Islands","synonyms":[]},
      |  {"cc":"MQ","name":"Martinique","synonyms":[]},
      |  {"cc":"MR","name":"Mauritania","synonyms":[]},
      |  {"cc":"MU","name":"Mauritius","synonyms":[]},
      |  {"cc":"YT","name":"Mayotte","synonyms":[]},
      |  {"cc":"MX","name":"Mexico","synonyms":[ "México" ]},
      |  {"cc":"FM","name":"Federated States of Micronesia","synonyms":[]},
      |  {"cc":"MD","name":"Moldova","synonyms":[]},
      |  {"cc":"MC","name":"Monaco","synonyms":[]},
      |  {"cc":"MN","name":"Mongolia","synonyms":[]},
      |  {"cc":"ME","name":"Montenegro","synonyms":[]},
      |  {"cc":"MS","name":"Montserrat","synonyms":[]},
      |  {"cc":"MA","name":"Morocco","synonyms":[]},
      |  {"cc":"MZ","name":"Mozambique","synonyms":[]},
      |  {"cc":"MM","name":"Myanmar","synonyms":[]},
      |  {"cc":"NA","name":"Namibia","synonyms":[]},
      |  {"cc":"NR","name":"Nauru","synonyms":[]},
      |  {"cc":"NP","name":"Nepal","synonyms":[]},
      |  {"cc":"NL","name":"Netherlands","synonyms":["Holland", "The Netherlands"]},
      |  {"cc":"NC","name":"New Caledonia","synonyms":[]},
      |  {"cc":"NZ","name":"New Zealand","synonyms":[]},
      |  {"cc":"NI","name":"Nicaragua","synonyms":[]},
      |  {"cc":"NE","name":"Niger","synonyms":[]},
      |  {"cc":"NG","name":"Nigeria","synonyms":[]},
      |  {"cc":"NU","name":"Niue","synonyms":[]},
      |  {"cc":"NF","name":"Norfolk Island","synonyms":[]},
      |  {"cc":"MP","name":"Northern Mariana Islands","synonyms":[]},
      |  {"cc":"NO","name":"Norway","synonyms":[]},
      |  {"cc":"OM","name":"Oman","synonyms":[]},
      |  {"cc":"PK","name":"Pakistan","synonyms":[]},
      |  {"cc":"PW","name":"Palau","synonyms":[]},
      |  {"cc":"PS","name":"Palestine","synonyms":[]},
      |  {"cc":"PA","name":"Panama","synonyms":[]},
      |  {"cc":"PG","name":"Papua New Guinea","synonyms":[]},
      |  {"cc":"PY","name":"Paraguay","synonyms":[]},
      |  {"cc":"PE","name":"Peru","synonyms":[]},
      |  {"cc":"PH","name":"Philippines","synonyms":[]},
      |  {"cc":"PN","name":"Pitcairn","synonyms":[]},
      |  {"cc":"PL","name":"Poland","synonyms":[]},
      |  {"cc":"PT","name":"Portugal","synonyms":[]},
      |  {"cc":"PR","name":"Puerto Rico","synonyms":[]},
      |  {"cc":"QA","name":"Qatar","synonyms":[]},
      |  {"cc":"RE","name":"Reunion","synonyms":[]},
      |  {"cc":"RO","name":"Romania","synonyms":[ "România" ]},
      |  {"cc":"RU","name":"Russia","synonyms":[]},
      |  {"cc":"RW","name":"Rwanda","synonyms":[]},
      |  {"cc":"BL","name":"Saint Barthélemy","synonyms":[]},
      |  {"cc":"SH","name":"Saint Helena Islands","synonyms":[]},
      |  {"cc":"KN","name":"Saint Kitts and Nevis","synonyms":[]},
      |  {"cc":"LC","name":"Saint Lucia","synonyms":[]},
      |  {"cc":"MF","name":"Saint Martin (French part)","synonyms":[]},
      |  {"cc":"PM","name":"Saint Pierre and Miquelon","synonyms":[]},
      |  {"cc":"VC","name":"Saint Vincent and the Grenadines","synonyms":[]},
      |  {"cc":"WS","name":"Samoa","synonyms":[]},
      |  {"cc":"SM","name":"San Marino","synonyms":[]},
      |  {"cc":"ST","name":"Sao Tome and Principe","synonyms":[]},
      |  {"cc":"SA","name":"Saudi Arabia","synonyms":[ "Kingdom of Saudi Arabia" ]},
      |  {"cc":"SN","name":"Senegal","synonyms":[]},
      |  {"cc":"RS","name":"Serbia","synonyms":[]},
      |  {"cc":"SC","name":"Seychelles","synonyms":[]},
      |  {"cc":"SL","name":"Sierra Leone","synonyms":[]},
      |  {"cc":"SG","name":"Singapore","synonyms":[]},
      |  {"cc":"SX","name":"Sint Maarten","synonyms":[]},
      |  {"cc":"SK","name":"Slovakia","synonyms":[]},
      |  {"cc":"SI","name":"Slovenia","synonyms":[]},
      |  {"cc":"SB","name":"Solomon Islands","synonyms":[]},
      |  {"cc":"SO","name":"Somalia","synonyms":[]},
      |  {"cc":"ZA","name":"South Africa","synonyms":[]},
      |  {"cc":"GS","name":"South Georgia and the South Sandwich Islands","synonyms":[]},
      |  {"cc":"GE","name":"Georgia","synonyms":[]},
      |  {"cc":"SS","name":"South Sudan","synonyms":[]},
      |  {"cc":"ES","name":"Spain","synonyms":[ "España" ]},
      |  {"cc":"LK","name":"Sri Lanka","synonyms":[]},
      |  {"cc":"SD","name":"Sudan","synonyms":[]},
      |  {"cc":"SR","name":"Suriname","synonyms":[]},
      |  {"cc":"SJ","name":"Svalbard and Jan Mayen","synonyms":[]},
      |  {"cc":"SZ","name":"Swaziland","synonyms":[]},
      |  {"cc":"SE","name":"Sweden","synonyms":[]},
      |  {"cc":"CH","name":"Switzerland","synonyms":[ "Suisse", "Schweiz" ]},
      |  {"cc":"SY","name":"Syria","synonyms":[]},
      |  {"cc":"TW","name":"Taiwan","synonyms":[ "R.O.C.", "R.O.C" ]},
      |  {"cc":"TJ","name":"Tajikistan","synonyms":[]},
      |  {"cc":"TZ","name":"Tanzania","synonyms":[]},
      |  {"cc":"TH","name":"Thailand","synonyms":[]},
      |  {"cc":"TL","name":"Timor-Leste","synonyms":["East Timor"]},
      |  {"cc":"TG","name":"Togo","synonyms":[]},
      |  {"cc":"TK","name":"Tokelau","synonyms":[]},
      |  {"cc":"TO","name":"Tonga","synonyms":[]},
      |  {"cc":"TT","name":"Trinidad and Tobago","synonyms":[]},
      |  {"cc":"TN","name":"Tunisia","synonyms":[]},
      |  {"cc":"TR","name":"Turkey","synonyms":[ "Türkei" ]},
      |  {"cc":"TM","name":"Turkmenistan","synonyms":[]},
      |  {"cc":"TC","name":"Turks and Caicos Islands","synonyms":[]},
      |  {"cc":"TV","name":"Tuvalu","synonyms":[]},
      |  {"cc":"UG","name":"Uganda","synonyms":[]},
      |  {"cc":"UA","name":"Ukraine","synonyms":[]},
      |  {"cc":"AE","name":"United Arab Emirates","synonyms":[]},
      |  {"cc":"GB","name":"United Kingdom","synonyms":["Great Britain", "UK", "U.K.", "U.K"]},
      |  {"cc":"US","name":"United States","synonyms":["United States of America", "USA", "U.S.A.", "U.S.A"]},
      |  {"cc":"UM","name":"United States Minor Outlying Islands","synonyms":[]},
      |  {"cc":"UY","name":"Uruguay","synonyms":[]},
      |  {"cc":"UZ","name":"Uzbekistan","synonyms":[]},
      |  {"cc":"VU","name":"Vanuatu","synonyms":[]},
      |  {"cc":"VE","name":"Venezuela","synonyms":[]},
      |  {"cc":"VN","name":"Vietnam","synonyms":[]},
      |  {"cc":"VG","name":"Virgin Islands British","synonyms":[]},
      |  {"cc":"VI","name":"Virgin Islands U.S.","synonyms":[]},
      |  {"cc":"WF","name":"Wallis and Futuna","synonyms":[]},
      |  {"cc":"EH","name":"Western Sahara","synonyms":[]},
      |  {"cc":"YE","name":"Yemen","synonyms":[]},
      |  {"cc":"ZM","name":"Zambia","synonyms":[]},
      |  {"cc":"ZW","name":"Zimbabwe","synonyms":[]}
      |]
      |
    """.stripMargin

  case class Country(cc:String, name:String, synonyms:Array[String])

  case class CountryIndexed(index:Int, c:Country)

  private val _Countries:Array[Country] = {
    import org.json4s.jackson.JsonMethods._
    implicit val fmt = DefaultFormats

    parse(jsons).extract[Array[Country]]
  }

  val countryMap:Map[Int, CountryIndexed] = _Countries.indices.map(idx => idx -> CountryIndexed(idx, _Countries(idx))).toMap

  val EmailPtn = "(?i)(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])".r

  val countryNameMap:Map[String, CountryIndexed] = countryMap.flatMap { p =>
    val names = p._2.c.name :: p._2.c.synonyms.toList
    names.map(_.toLowerCase() -> p._2)
  }

  def sameCountryInLine(line:Array[String], l:String):String = {
    val allCountries = line.filter(countryNameMap.contains)
    if (allCountries.length == 0)
      EmptyCountry
    else if (allCountries.distinct.length > 1) {
      println(s"Mutiple countries: ${allCountries.mkString(",")} in [$l]")
      EmptyCountry
    }
    else allCountries(0)
    //allCountries.mkString(",")
  }

  private val EmptyCountry = ""
  def lineEndWithCountry(line:Array[String]):String = {
    var revIdx = line.length-1
    while (revIdx >= 0 && EmailPtn.pattern.matcher(line(revIdx)).matches()) {
      revIdx -= 1
    }
    if (revIdx >= 0) {
      if (countryNameMap.contains(line(revIdx)))
        line(revIdx)
      else EmptyCountry
    }
    else EmptyCountry
  }
}
